// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzirvmskmngdikxkfdip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6aXJ2bXNrbW5nZGlreGtmZGlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY0MDkyOTgsImV4cCI6MjA5MTk4NTI5OH0.h5eV6cfGAAXt4shiLz2S1ccsAIXm0JzR5zucav9iTxk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});